# Botones de donación que muestra GitHub en el repo.
github: [leostriker111]     # requiere activar GitHub Sponsors en tu cuenta
ko_fi:                      # pon aqui tu usuario de Ko-fi, ej: leonardoaguayo
